#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p $GOPATH/src/github.com/hermanjunge/
rm -rf $GOPATH/src/github.com/hermanjunge/devp2p-concept
cp -R $CURRENT_DIR $GOPATH/src/github.com/hermanjunge/devp2p-concept

cd $GOPATH/src/github.com/hermanjunge/devp2p-concept
go build -v -o ejemplo *.go && ./ejemplo "$@"
