#!/bin/bash

echo NOT IMPLEMENTED

# Query the Parity JSON RPC API
# curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x3df070", true],"id":1}' http://localhost:8545

# extract the block hash
# TODO

# cid it
# TODO

# Query the Parity IPFS API
# TODO

# Output the response
# TODO
